import React, { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import {
  ArrowRight,
  CircleAlert,
  CircleCheckBig,
  Loader2,
  LockKeyhole,
  TimerReset,
} from 'lucide-react';
import BrandMark from '../components/BrandMark';
import { CommandWindow, Reveal } from '../components/ui';

const API = import.meta.env.VITE_API_BASE_URL || 'https://api.dabcloud.in';

function Countdown({ seconds }) {
  const minutes = Math.floor(seconds / 60).toString().padStart(2, '0');
  const remainder = (seconds % 60).toString().padStart(2, '0');
  const urgent = seconds <= 60 && seconds > 0;

  return (
    <span
      className="inline-code"
      style={urgent ? { color: 'var(--warning, #f2c572)', borderColor: 'rgba(242,197,114,0.4)' } : undefined}
    >
      {minutes}:{remainder}
    </span>
  );
}

export default function CliAuth() {
  const [params] = useSearchParams();
  const userCode = params.get('user_code') || '';

  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const [status, setStatus] = useState('idle');
  const [errMsg, setErrMsg] = useState('');
  const [timeLeft, setTimeLeft] = useState(600);

  useEffect(() => {
    if (timeLeft === 0) return;
    const id = window.setTimeout(() => {
      setTimeLeft((value) => Math.max(0, value - 1));
    }, 1000);
    return () => window.clearTimeout(id);
  }, [timeLeft]);

  const expired = timeLeft === 0;
  const missingCode = !userCode;
  const blocked = expired || missingCode;

  const handleRetry = () => {
    setStatus('idle');
    setErrMsg('');
  };

  const errorMessage = useMemo(() => {
    if (missingCode) {
      return 'No device code was attached to this page. Run krud login again from your terminal.';
    }
    if (expired) {
      return 'This device code expired. Run krud login again to generate a fresh approval request.';
    }
    return errMsg;
  }, [errMsg, expired, missingCode]);

  const handleSubmit = async (event) => {
    event.preventDefault();

    if (blocked) {
      return;
    }

    setStatus('loading');
    setErrMsg('');

    try {
      const payload = new FormData();
      payload.append('user_code', userCode);
      payload.append('email', email);
      if (name) {
        payload.append('name', name);
      }

      const response = await fetch(`${API}/cli-auth`, {
        method: 'POST',
        body: payload,
      });

      if (response.ok) {
        setStatus('success');
        return;
      }

      setStatus('error');
      setErrMsg('Invalid or expired code. Please run krud login again.');
    } catch {
      setStatus('network-error');
      setErrMsg('Network error. Check your connection and try again.');
    }
  };

  return (
    <div className="auth-shell">
      <div className="site-ambient" aria-hidden="true">
        <span className="site-ambient__glow site-ambient__glow-primary" />
        <span className="site-ambient__glow site-ambient__glow-secondary" />
        <span className="site-ambient__grid" />
      </div>

      <header className="auth-header">
        <div className="shell auth-header__inner">
          <Link to="/" className="brand-link">
            <BrandMark />
          </Link>
          <Link to="/" className="button button-secondary">
            Back to site
          </Link>
        </div>
      </header>

      <main className="shell auth-main">
        <Reveal className="auth-copy">
          <p className="section-eyebrow">Device approval</p>
          <h1 style={{ fontSize: 'clamp(2.6rem, 7vw, 5.3rem)' }}>Approve this terminal session.</h1>
          <p className="page-intro__description">
            This page exists for one job only: confirm that the terminal session you just
            started should be allowed to continue.
          </p>

          <ul className="detail-list">
            <li>Approve only if you just ran <span className="inline-code">krud login</span>.</li>
            <li>The device code is generated by the terminal and attached to this request.</li>
            <li>After approval, return to the CLI and continue directly into chat.</li>
          </ul>

          <div className="hero-notes" style={{ marginTop: '1.5rem' }}>
            <span className="status-pill">
              <LockKeyhole size={14} />
              Browser step is only for confirmation
            </span>
            <span className="status-pill">
              <TimerReset size={14} />
              Expires after a short window
            </span>
          </div>
        </Reveal>

        <Reveal delay={0.1} className="auth-panel">
          {status === 'success' ? (
            <div className="auth-success">
              <span className="status-pill">
                <CircleCheckBig size={14} />
                Approved
              </span>
              <strong>Terminal connected for {email}.</strong>
              <p>Switch back to the CLI. The session is ready and you can close this tab.</p>
              <CommandWindow
                title="next step"
                label="ready"
                lines={[
                  { kind: 'command', text: 'krud chat' },
                  { kind: 'prompt', text: 'explain the last failed deploy in plain English' },
                  { kind: 'success', text: 'You are authenticated and ready to continue.' },
                ]}
              />
            </div>
          ) : (
            <>
              {(status === 'error' || status === 'network-error' || blocked) ? (
                <div className="auth-alert">
                  <p style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--text)' }}>
                    <CircleAlert size={16} />
                    {errorMessage}
                  </p>
                  {status === 'network-error' && (
                    <button
                      type="button"
                      className="button button-secondary"
                      style={{ marginTop: '0.6rem', width: '100%' }}
                      onClick={handleRetry}
                    >
                      Try again
                    </button>
                  )}
                </div>
              ) : null}

              <div className="auth-code">
                <div className="auth-code__meta">
                  <span>Device code</span>
                  <span>Expires in <Countdown seconds={timeLeft} /></span>
                </div>
                <div className="auth-code__value">{userCode || 'XXXX-XXXX'}</div>
                <div className="auth-code__meta">
                  <span>Auto-filled from your terminal</span>
                  <span>{blocked ? 'Needs a fresh request' : 'Ready to approve'}</span>
                </div>
              </div>

              <form onSubmit={handleSubmit} className="form-stack">
                <div className="field">
                  <label htmlFor="email">Email</label>
                  <input
                    id="email"
                    type="email"
                    required
                    placeholder="you@company.com"
                    value={email}
                    onChange={(event) => setEmail(event.target.value)}
                    disabled={status === 'loading' || blocked}
                  />
                </div>
                <div className="field">
                  <label htmlFor="name">Name (optional)</label>
                  <input
                    id="name"
                    type="text"
                    placeholder="Your name"
                    value={name}
                    onChange={(event) => setName(event.target.value)}
                    disabled={status === 'loading' || blocked}
                  />
                </div>
                <button
                  type="submit"
                  className="button button-primary"
                  style={{ width: '100%' }}
                  disabled={status === 'loading' || blocked}
                >
                  {status === 'loading' ? (
                    <>
                      <Loader2 size={15} style={{ animation: 'spin 1s linear infinite' }} />
                      Approving…
                    </>
                  ) : (
                    <>
                      Approve device
                      <ArrowRight size={15} />
                    </>
                  )}
                </button>
              </form>

              <p className="auth-note">
                If this page was opened without a valid code, run <span className="inline-code">krud login</span> again from the terminal.
              </p>
            </>
          )}
        </Reveal>
      </main>
    </div>
  );
}
